name: TinyProxy Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tinyproxy
        repository: tinyproxy/tinyproxy
    - name: autogen
      run: ./autogen
    - name: configure
      run: ./configure LDFLAGS="-static" --enable-manpage_support=no
    - name: make
      run: make
